/* tslint:disable */
/* eslint-disable */
/**
 * Balaur SMS API
 * Software Management System para gestión, distribución y control de software universitario.  ## Características - Gestión de software con múltiples versiones - Sistema de archivos con FTP y validación SHA-256 - Licencias cifradas con AES-GCM - RBAC con 4 roles (Admin, Gestor, Usuario, Invitado) - Auditoría completa de operaciones - FTP Watcher automático para procesamiento de archivos  ## Autenticación La API utiliza JWT (Bearer tokens) con dos tipos de token: - **Access Token**: Válido 15 minutos - **Refresh Token**: Válido 7 días  ## Flujo de subida de instaladores 1. Usuario sube archivo vía FTP a `/inbox/pending/` 2. FTP Watcher procesa automáticamente (cada 5 min):    - Valida extensión y tamaño    - Calcula SHA-256    - Mueve a `/inbox/processing/` (si válido) o `/quarantine/` (si inválido) 3. Usuario registra instalador vía `POST /installers` con el SHA-256 4. Sistema organiza archivo en `/repository/software_id/version/` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@university.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { AuditAction } from '../models';
// @ts-ignore
import { AuditLogListResponse } from '../models';
// @ts-ignore
import { ErrorResponse } from '../models';
/**
 * AuditApi - axios parameter creator
 * @export
 */
export const AuditApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Solo Administrador. Soporta filtros y paginación. Los logs se registran automáticamente por el middleware. 
         * @summary Consultar logs de auditoría
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {number} [userId] Filtrar por usuario
         * @param {AuditAction} [action] 
         * @param {string} [resourceType] Tipo de recurso (software, installer, license)
         * @param {string} [dateFrom] 
         * @param {string} [dateTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditLogs: async (page?: number, pageSize?: number, userId?: number, action?: AuditAction, resourceType?: string, dateFrom?: string, dateTo?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/audit/logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (action !== undefined) {
                localVarQueryParameter['action'] = action;
            }

            if (resourceType !== undefined) {
                localVarQueryParameter['resource_type'] = resourceType;
            }

            if (dateFrom !== undefined) {
                localVarQueryParameter['date_from'] = (dateFrom as any instanceof Date) ?
                    (dateFrom as any).toISOString() :
                    dateFrom;
            }

            if (dateTo !== undefined) {
                localVarQueryParameter['date_to'] = (dateTo as any instanceof Date) ?
                    (dateTo as any).toISOString() :
                    dateTo;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuditApi - functional programming interface
 * @export
 */
export const AuditApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuditApiAxiosParamCreator(configuration)
    return {
        /**
         * Solo Administrador. Soporta filtros y paginación. Los logs se registran automáticamente por el middleware. 
         * @summary Consultar logs de auditoría
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {number} [userId] Filtrar por usuario
         * @param {AuditAction} [action] 
         * @param {string} [resourceType] Tipo de recurso (software, installer, license)
         * @param {string} [dateFrom] 
         * @param {string} [dateTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuditLogs(page?: number, pageSize?: number, userId?: number, action?: AuditAction, resourceType?: string, dateFrom?: string, dateTo?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditLogListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuditLogs(page, pageSize, userId, action, resourceType, dateFrom, dateTo, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AuditApi.getAuditLogs']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * AuditApi - factory interface
 * @export
 */
export const AuditApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuditApiFp(configuration)
    return {
        /**
         * Solo Administrador. Soporta filtros y paginación. Los logs se registran automáticamente por el middleware. 
         * @summary Consultar logs de auditoría
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {number} [userId] Filtrar por usuario
         * @param {AuditAction} [action] 
         * @param {string} [resourceType] Tipo de recurso (software, installer, license)
         * @param {string} [dateFrom] 
         * @param {string} [dateTo] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditLogs(page?: number, pageSize?: number, userId?: number, action?: AuditAction, resourceType?: string, dateFrom?: string, dateTo?: string, options?: any): AxiosPromise<AuditLogListResponse> {
            return localVarFp.getAuditLogs(page, pageSize, userId, action, resourceType, dateFrom, dateTo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuditApi - object-oriented interface
 * @export
 * @class AuditApi
 * @extends {BaseAPI}
 */
export class AuditApi extends BaseAPI {
    /**
     * Solo Administrador. Soporta filtros y paginación. Los logs se registran automáticamente por el middleware. 
     * @summary Consultar logs de auditoría
     * @param {number} [page] Número de página (1-indexed)
     * @param {number} [pageSize] Elementos por página
     * @param {number} [userId] Filtrar por usuario
     * @param {AuditAction} [action] 
     * @param {string} [resourceType] Tipo de recurso (software, installer, license)
     * @param {string} [dateFrom] 
     * @param {string} [dateTo] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public getAuditLogs(page?: number, pageSize?: number, userId?: number, action?: AuditAction, resourceType?: string, dateFrom?: string, dateTo?: string, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).getAuditLogs(page, pageSize, userId, action, resourceType, dateFrom, dateTo, options).then((request) => request(this.axios, this.basePath));
    }
}

// ✅ EXPORT para que otros módulos accedan al tipo
export type { AuditLogResponse } from '../models';