/* tslint:disable */
/* eslint-disable */
/**
 * Balaur SMS API
 * Software Management System para gestión, distribución y control de software universitario.  ## Características - Gestión de software con múltiples versiones - Sistema de archivos con FTP y validación SHA-256 - Licencias cifradas con AES-GCM - RBAC con 4 roles (Admin, Gestor, Usuario, Invitado) - Auditoría completa de operaciones - FTP Watcher automático para procesamiento de archivos  ## Autenticación La API utiliza JWT (Bearer tokens) con dos tipos de token: - **Access Token**: Válido 15 minutos - **Refresh Token**: Válido 7 días  ## Flujo de subida de instaladores 1. Usuario sube archivo vía FTP a `/inbox/pending/` 2. FTP Watcher procesa automáticamente (cada 5 min):    - Valida extensión y tamaño    - Calcula SHA-256    - Mueve a `/inbox/processing/` (si válido) o `/quarantine/` (si inválido) 3. Usuario registra instalador vía `POST /installers` con el SHA-256 4. Sistema organiza archivo en `/repository/software_id/version/` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@university.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ErrorResponse } from '../models';
// @ts-ignore
import { InstallerCreateRequest } from '../models';
// @ts-ignore
import { InstallerResponse } from '../models';
// @ts-ignore
import { ListInstallers200Response } from '../models';
// @ts-ignore
import { ListSoftwareInstallers200Response } from '../models';
// @ts-ignore
import { ValidationErrorResponse } from '../models';
/**
 * InstallersApi - axios parameter creator
 * @export
 */
export const InstallersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Solo Administrador. Elimina archivo del FTP y registro de BD. El archivo físico se elimina permanentemente. 
         * @summary Eliminar instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInstaller: async (installerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'installerId' is not null or undefined
            assertParamExists('deleteInstaller', 'installerId', installerId)
            const localVarPath = `/installers/{installer_id}`
                .replace(`{${"installer_id"}}`, encodeURIComponent(String(installerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Descarga archivo mediante streaming (no carga en memoria completa). Usuarios con rol \"Usuario\" o superior pueden descargar. Registra descarga en audit log automáticamente. Incrementa contador de descargas. 
         * @summary Descargar instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadInstaller: async (installerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'installerId' is not null or undefined
            assertParamExists('downloadInstaller', 'installerId', installerId)
            const localVarPath = `/installers/{installer_id}/download`
                .replace(`{${"installer_id"}}`, encodeURIComponent(String(installerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Obtener información del instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInstaller: async (installerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'installerId' is not null or undefined
            assertParamExists('getInstaller', 'installerId', installerId)
            const localVarPath = `/installers/{installer_id}`
                .replace(`{${"installer_id"}}`, encodeURIComponent(String(installerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retorna una lista completa de installers registrados.
         * @summary Listar todos los installers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInstallers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/installers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar instaladores de un software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSoftwareInstallers: async (softwareId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'softwareId' is not null or undefined
            assertParamExists('listSoftwareInstallers', 'softwareId', softwareId)
            const localVarPath = `/software/{software_id}/installers`
                .replace(`{${"software_id"}}`, encodeURIComponent(String(softwareId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Registra un instalador después de subirlo vía FTP. Solo Gestor y Administrador.  **Flujo completo:** 1. Usuario sube archivo a FTP inbox/pending/ 2. Watcher procesa automáticamente (valida, calcula SHA-256) 3. Watcher mueve a inbox/processing/ si es válido 4. Usuario obtiene SHA-256 del archivo procesado 5. Usuario llama este endpoint con el SHA-256 6. Sistema busca archivo en processing/ por filename 7. Sistema mueve archivo a repository/software_id/version/ 8. Sistema registra en base de datos  **IMPORTANTE:** El archivo debe estar en inbox/processing/ antes de llamar este endpoint. 
         * @summary Registrar instalador
         * @param {InstallerCreateRequest} installerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerInstaller: async (installerCreateRequest: InstallerCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'installerCreateRequest' is not null or undefined
            assertParamExists('registerInstaller', 'installerCreateRequest', installerCreateRequest)
            const localVarPath = `/installers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(installerCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InstallersApi - functional programming interface
 * @export
 */
export const InstallersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InstallersApiAxiosParamCreator(configuration)
    return {
        /**
         * Solo Administrador. Elimina archivo del FTP y registro de BD. El archivo físico se elimina permanentemente. 
         * @summary Eliminar instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteInstaller(installerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteInstaller(installerId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['InstallersApi.deleteInstaller']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Descarga archivo mediante streaming (no carga en memoria completa). Usuarios con rol \"Usuario\" o superior pueden descargar. Registra descarga en audit log automáticamente. Incrementa contador de descargas. 
         * @summary Descargar instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadInstaller(installerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadInstaller(installerId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['InstallersApi.downloadInstaller']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Obtener información del instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInstaller(installerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InstallerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInstaller(installerId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['InstallersApi.getInstaller']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Retorna una lista completa de installers registrados.
         * @summary Listar todos los installers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listInstallers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListInstallers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listInstallers(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['InstallersApi.listInstallers']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Listar instaladores de un software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSoftwareInstallers(softwareId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSoftwareInstallers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSoftwareInstallers(softwareId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['InstallersApi.listSoftwareInstallers']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Registra un instalador después de subirlo vía FTP. Solo Gestor y Administrador.  **Flujo completo:** 1. Usuario sube archivo a FTP inbox/pending/ 2. Watcher procesa automáticamente (valida, calcula SHA-256) 3. Watcher mueve a inbox/processing/ si es válido 4. Usuario obtiene SHA-256 del archivo procesado 5. Usuario llama este endpoint con el SHA-256 6. Sistema busca archivo en processing/ por filename 7. Sistema mueve archivo a repository/software_id/version/ 8. Sistema registra en base de datos  **IMPORTANTE:** El archivo debe estar en inbox/processing/ antes de llamar este endpoint. 
         * @summary Registrar instalador
         * @param {InstallerCreateRequest} installerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerInstaller(installerCreateRequest: InstallerCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InstallerResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerInstaller(installerCreateRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['InstallersApi.registerInstaller']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * InstallersApi - factory interface
 * @export
 */
export const InstallersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InstallersApiFp(configuration)
    return {
        /**
         * Solo Administrador. Elimina archivo del FTP y registro de BD. El archivo físico se elimina permanentemente. 
         * @summary Eliminar instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInstaller(installerId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteInstaller(installerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Descarga archivo mediante streaming (no carga en memoria completa). Usuarios con rol \"Usuario\" o superior pueden descargar. Registra descarga en audit log automáticamente. Incrementa contador de descargas. 
         * @summary Descargar instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadInstaller(installerId: number, options?: any): AxiosPromise<File> {
            return localVarFp.downloadInstaller(installerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Obtener información del instalador
         * @param {number} installerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInstaller(installerId: number, options?: any): AxiosPromise<InstallerResponse> {
            return localVarFp.getInstaller(installerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retorna una lista completa de installers registrados.
         * @summary Listar todos los installers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInstallers(options?: any): AxiosPromise<ListInstallers200Response> {
            return localVarFp.listInstallers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar instaladores de un software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSoftwareInstallers(softwareId: number, options?: any): AxiosPromise<ListSoftwareInstallers200Response> {
            return localVarFp.listSoftwareInstallers(softwareId, options).then((request) => request(axios, basePath));
        },
        /**
         * Registra un instalador después de subirlo vía FTP. Solo Gestor y Administrador.  **Flujo completo:** 1. Usuario sube archivo a FTP inbox/pending/ 2. Watcher procesa automáticamente (valida, calcula SHA-256) 3. Watcher mueve a inbox/processing/ si es válido 4. Usuario obtiene SHA-256 del archivo procesado 5. Usuario llama este endpoint con el SHA-256 6. Sistema busca archivo en processing/ por filename 7. Sistema mueve archivo a repository/software_id/version/ 8. Sistema registra en base de datos  **IMPORTANTE:** El archivo debe estar en inbox/processing/ antes de llamar este endpoint. 
         * @summary Registrar instalador
         * @param {InstallerCreateRequest} installerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerInstaller(installerCreateRequest: InstallerCreateRequest, options?: any): AxiosPromise<InstallerResponse> {
            return localVarFp.registerInstaller(installerCreateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InstallersApi - object-oriented interface
 * @export
 * @class InstallersApi
 * @extends {BaseAPI}
 */
export class InstallersApi extends BaseAPI {
    /**
     * Solo Administrador. Elimina archivo del FTP y registro de BD. El archivo físico se elimina permanentemente. 
     * @summary Eliminar instalador
     * @param {number} installerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstallersApi
     */
    public deleteInstaller(installerId: number, options?: RawAxiosRequestConfig) {
        return InstallersApiFp(this.configuration).deleteInstaller(installerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Descarga archivo mediante streaming (no carga en memoria completa). Usuarios con rol \"Usuario\" o superior pueden descargar. Registra descarga en audit log automáticamente. Incrementa contador de descargas. 
     * @summary Descargar instalador
     * @param {number} installerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstallersApi
     */
    public downloadInstaller(installerId: number, options?: RawAxiosRequestConfig) {
        return InstallersApiFp(this.configuration).downloadInstaller(installerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Obtener información del instalador
     * @param {number} installerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstallersApi
     */
    public getInstaller(installerId: number, options?: RawAxiosRequestConfig) {
        return InstallersApiFp(this.configuration).getInstaller(installerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retorna una lista completa de installers registrados.
     * @summary Listar todos los installers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstallersApi
     */
    public listInstallers(options?: RawAxiosRequestConfig) {
        return InstallersApiFp(this.configuration).listInstallers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar instaladores de un software
     * @param {number} softwareId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstallersApi
     */
    public listSoftwareInstallers(softwareId: number, options?: RawAxiosRequestConfig) {
        return InstallersApiFp(this.configuration).listSoftwareInstallers(softwareId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Registra un instalador después de subirlo vía FTP. Solo Gestor y Administrador.  **Flujo completo:** 1. Usuario sube archivo a FTP inbox/pending/ 2. Watcher procesa automáticamente (valida, calcula SHA-256) 3. Watcher mueve a inbox/processing/ si es válido 4. Usuario obtiene SHA-256 del archivo procesado 5. Usuario llama este endpoint con el SHA-256 6. Sistema busca archivo en processing/ por filename 7. Sistema mueve archivo a repository/software_id/version/ 8. Sistema registra en base de datos  **IMPORTANTE:** El archivo debe estar en inbox/processing/ antes de llamar este endpoint. 
     * @summary Registrar instalador
     * @param {InstallerCreateRequest} installerCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstallersApi
     */
    public registerInstaller(installerCreateRequest: InstallerCreateRequest, options?: RawAxiosRequestConfig) {
        return InstallersApiFp(this.configuration).registerInstaller(installerCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

// ✅ EXPORT para que otros módulos accedan al tipo
export type { InstallerResponse, InstallerCreateRequest, ListInstallers200Response, ListSoftwareInstallers200Response } from '../models';

