/* tslint:disable */
/* eslint-disable */
/**
 * Balaur SMS API
 * Software Management System para gestión, distribución y control de software universitario.  ## Características - Gestión de software con múltiples versiones - Sistema de archivos con FTP y validación SHA-256 - Licencias cifradas con AES-GCM - RBAC con 4 roles (Admin, Gestor, Usuario, Invitado) - Auditoría completa de operaciones - FTP Watcher automático para procesamiento de archivos  ## Autenticación La API utiliza JWT (Bearer tokens) con dos tipos de token: - **Access Token**: Válido 15 minutos - **Refresh Token**: Válido 7 días  ## Flujo de subida de instaladores 1. Usuario sube archivo vía FTP a `/inbox/pending/` 2. FTP Watcher procesa automáticamente (cada 5 min):    - Valida extensión y tamaño    - Calcula SHA-256    - Mueve a `/inbox/processing/` (si válido) o `/quarantine/` (si inválido) 3. Usuario registra instalador vía `POST /installers` con el SHA-256 4. Sistema organiza archivo en `/repository/software_id/version/` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@university.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ErrorResponse } from '../models';
// @ts-ignore
import { LicenseCreateRequest } from '../models';
// @ts-ignore
import { LicenseDetailResponse } from '../models';
// @ts-ignore
import { LicenseListResponse } from '../models';
// @ts-ignore
import { LicenseResponse } from '../models';
// @ts-ignore
import { LicenseUpdateRequest } from '../models';
// @ts-ignore
import { ValidationErrorResponse } from '../models';
/**
 * LicensesApi - axios parameter creator
 * @export
 */
export const LicensesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Solo Administrador. Cifra automáticamente la clave con AES-GCM. La clave se almacena cifrada y solo se descifra en GET individual. 
         * @summary Crear licencia
         * @param {LicenseCreateRequest} licenseCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLicense: async (licenseCreateRequest: LicenseCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'licenseCreateRequest' is not null or undefined
            assertParamExists('createLicense', 'licenseCreateRequest', licenseCreateRequest)
            const localVarPath = `/licenses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(licenseCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Solo Administrador. Eliminación permanente, la clave cifrada se pierde irrecuperablemente. 
         * @summary Eliminar licencia
         * @param {number} licenseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLicense: async (licenseId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'licenseId' is not null or undefined
            assertParamExists('deleteLicense', 'licenseId', licenseId)
            const localVarPath = `/licenses/{license_id}`
                .replace(`{${"license_id"}}`, encodeURIComponent(String(licenseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Solo Administrador. Devuelve clave descifrada. **IMPORTANTE:** Este acceso se registra en audit log automáticamente. 
         * @summary Obtener licencia con clave descifrada
         * @param {number} licenseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLicense: async (licenseId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'licenseId' is not null or undefined
            assertParamExists('getLicense', 'licenseId', licenseId)
            const localVarPath = `/licenses/{license_id}`
                .replace(`{${"license_id"}}`, encodeURIComponent(String(licenseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Solo Administrador. Claves cifradas NO se devuelven en listado por seguridad. Use GET individual para obtener clave descifrada. 
         * @summary Listar licencias
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {number} [softwareId] Filtrar por software
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listLicenses: async (page?: number, pageSize?: number, softwareId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/licenses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (softwareId !== undefined) {
                localVarQueryParameter['software_id'] = softwareId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Solo Administrador. Si se proporciona nueva clave, se cifra automáticamente. 
         * @summary Actualizar licencia
         * @param {number} licenseId 
         * @param {LicenseUpdateRequest} licenseUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLicense: async (licenseId: number, licenseUpdateRequest: LicenseUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'licenseId' is not null or undefined
            assertParamExists('updateLicense', 'licenseId', licenseId)
            // verify required parameter 'licenseUpdateRequest' is not null or undefined
            assertParamExists('updateLicense', 'licenseUpdateRequest', licenseUpdateRequest)
            const localVarPath = `/licenses/{license_id}`
                .replace(`{${"license_id"}}`, encodeURIComponent(String(licenseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(licenseUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LicensesApi - functional programming interface
 * @export
 */
export const LicensesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LicensesApiAxiosParamCreator(configuration)
    return {
        /**
         * Solo Administrador. Cifra automáticamente la clave con AES-GCM. La clave se almacena cifrada y solo se descifra en GET individual. 
         * @summary Crear licencia
         * @param {LicenseCreateRequest} licenseCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createLicense(licenseCreateRequest: LicenseCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LicenseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createLicense(licenseCreateRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['LicensesApi.createLicense']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Solo Administrador. Eliminación permanente, la clave cifrada se pierde irrecuperablemente. 
         * @summary Eliminar licencia
         * @param {number} licenseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLicense(licenseId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLicense(licenseId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['LicensesApi.deleteLicense']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Solo Administrador. Devuelve clave descifrada. **IMPORTANTE:** Este acceso se registra en audit log automáticamente. 
         * @summary Obtener licencia con clave descifrada
         * @param {number} licenseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLicense(licenseId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LicenseDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLicense(licenseId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['LicensesApi.getLicense']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Solo Administrador. Claves cifradas NO se devuelven en listado por seguridad. Use GET individual para obtener clave descifrada. 
         * @summary Listar licencias
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {number} [softwareId] Filtrar por software
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listLicenses(page?: number, pageSize?: number, softwareId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LicenseListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listLicenses(page, pageSize, softwareId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['LicensesApi.listLicenses']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Solo Administrador. Si se proporciona nueva clave, se cifra automáticamente. 
         * @summary Actualizar licencia
         * @param {number} licenseId 
         * @param {LicenseUpdateRequest} licenseUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateLicense(licenseId: number, licenseUpdateRequest: LicenseUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LicenseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateLicense(licenseId, licenseUpdateRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['LicensesApi.updateLicense']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * LicensesApi - factory interface
 * @export
 */
export const LicensesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LicensesApiFp(configuration)
    return {
        /**
         * Solo Administrador. Cifra automáticamente la clave con AES-GCM. La clave se almacena cifrada y solo se descifra en GET individual. 
         * @summary Crear licencia
         * @param {LicenseCreateRequest} licenseCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLicense(licenseCreateRequest: LicenseCreateRequest, options?: any): AxiosPromise<LicenseResponse> {
            return localVarFp.createLicense(licenseCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Solo Administrador. Eliminación permanente, la clave cifrada se pierde irrecuperablemente. 
         * @summary Eliminar licencia
         * @param {number} licenseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLicense(licenseId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteLicense(licenseId, options).then((request) => request(axios, basePath));
        },
        /**
         * Solo Administrador. Devuelve clave descifrada. **IMPORTANTE:** Este acceso se registra en audit log automáticamente. 
         * @summary Obtener licencia con clave descifrada
         * @param {number} licenseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLicense(licenseId: number, options?: any): AxiosPromise<LicenseDetailResponse> {
            return localVarFp.getLicense(licenseId, options).then((request) => request(axios, basePath));
        },
        /**
         * Solo Administrador. Claves cifradas NO se devuelven en listado por seguridad. Use GET individual para obtener clave descifrada. 
         * @summary Listar licencias
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {number} [softwareId] Filtrar por software
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listLicenses(page?: number, pageSize?: number, softwareId?: number, options?: any): AxiosPromise<LicenseListResponse> {
            return localVarFp.listLicenses(page, pageSize, softwareId, options).then((request) => request(axios, basePath));
        },
        /**
         * Solo Administrador. Si se proporciona nueva clave, se cifra automáticamente. 
         * @summary Actualizar licencia
         * @param {number} licenseId 
         * @param {LicenseUpdateRequest} licenseUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateLicense(licenseId: number, licenseUpdateRequest: LicenseUpdateRequest, options?: any): AxiosPromise<LicenseResponse> {
            return localVarFp.updateLicense(licenseId, licenseUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LicensesApi - object-oriented interface
 * @export
 * @class LicensesApi
 * @extends {BaseAPI}
 */
export class LicensesApi extends BaseAPI {
    /**
     * Solo Administrador. Cifra automáticamente la clave con AES-GCM. La clave se almacena cifrada y solo se descifra en GET individual. 
     * @summary Crear licencia
     * @param {LicenseCreateRequest} licenseCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicensesApi
     */
    public createLicense(licenseCreateRequest: LicenseCreateRequest, options?: RawAxiosRequestConfig) {
        return LicensesApiFp(this.configuration).createLicense(licenseCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Solo Administrador. Eliminación permanente, la clave cifrada se pierde irrecuperablemente. 
     * @summary Eliminar licencia
     * @param {number} licenseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicensesApi
     */
    public deleteLicense(licenseId: number, options?: RawAxiosRequestConfig) {
        return LicensesApiFp(this.configuration).deleteLicense(licenseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Solo Administrador. Devuelve clave descifrada. **IMPORTANTE:** Este acceso se registra en audit log automáticamente. 
     * @summary Obtener licencia con clave descifrada
     * @param {number} licenseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicensesApi
     */
    public getLicense(licenseId: number, options?: RawAxiosRequestConfig) {
        return LicensesApiFp(this.configuration).getLicense(licenseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Solo Administrador. Claves cifradas NO se devuelven en listado por seguridad. Use GET individual para obtener clave descifrada. 
     * @summary Listar licencias
     * @param {number} [page] Número de página (1-indexed)
     * @param {number} [pageSize] Elementos por página
     * @param {number} [softwareId] Filtrar por software
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicensesApi
     */
    public listLicenses(page?: number, pageSize?: number, softwareId?: number, options?: RawAxiosRequestConfig) {
        return LicensesApiFp(this.configuration).listLicenses(page, pageSize, softwareId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Solo Administrador. Si se proporciona nueva clave, se cifra automáticamente. 
     * @summary Actualizar licencia
     * @param {number} licenseId 
     * @param {LicenseUpdateRequest} licenseUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LicensesApi
     */
    public updateLicense(licenseId: number, licenseUpdateRequest: LicenseUpdateRequest, options?: RawAxiosRequestConfig) {
        return LicensesApiFp(this.configuration).updateLicense(licenseId, licenseUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

// ✅ EXPORT para que otros módulos accedan al tipo
export type { LicenseResponse } from '../models';