/* tslint:disable */
/* eslint-disable */
/**
 * Balaur SMS API
 * Software Management System para gestión, distribución y control de software universitario.  ## Características - Gestión de software con múltiples versiones - Sistema de archivos con FTP y validación SHA-256 - Licencias cifradas con AES-GCM - RBAC con 4 roles (Admin, Gestor, Usuario, Invitado) - Auditoría completa de operaciones - FTP Watcher automático para procesamiento de archivos  ## Autenticación La API utiliza JWT (Bearer tokens) con dos tipos de token: - **Access Token**: Válido 15 minutos - **Refresh Token**: Válido 7 días  ## Flujo de subida de instaladores 1. Usuario sube archivo vía FTP a `/inbox/pending/` 2. FTP Watcher procesa automáticamente (cada 5 min):    - Valida extensión y tamaño    - Calcula SHA-256    - Mueve a `/inbox/processing/` (si válido) o `/quarantine/` (si inválido) 3. Usuario registra instalador vía `POST /installers` con el SHA-256 4. Sistema organiza archivo en `/repository/software_id/version/` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@university.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { ErrorResponse } from '../models';
// @ts-ignore
import { ListSoftwareInstallers200Response } from '../models';
// @ts-ignore
import { SoftwareCreateRequest } from '../models';
// @ts-ignore
import { SoftwareDetailResponse } from '../models';
// @ts-ignore
import { SoftwareListResponse } from '../models';
// @ts-ignore
import { SoftwareResponse } from '../models';
// @ts-ignore
import { SoftwareUpdateRequest } from '../models';
// @ts-ignore
import { ValidationErrorResponse } from '../models';
/**
 * SoftwareApi - axios parameter creator
 * @export
 */
export const SoftwareApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Solo Gestor y Administrador.
         * @summary Crear software
         * @param {SoftwareCreateRequest} softwareCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSoftware: async (softwareCreateRequest: SoftwareCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'softwareCreateRequest' is not null or undefined
            assertParamExists('createSoftware', 'softwareCreateRequest', softwareCreateRequest)
            const localVarPath = `/software`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(softwareCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Solo Administrador. Elimina software y todos sus instaladores asociados (cascade). Los archivos físicos en FTP se eliminan también. 
         * @summary Eliminar software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSoftware: async (softwareId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'softwareId' is not null or undefined
            assertParamExists('deleteSoftware', 'softwareId', softwareId)
            const localVarPath = `/software/{software_id}`
                .replace(`{${"software_id"}}`, encodeURIComponent(String(softwareId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Detalles del software con lista de instaladores. Licencias solo visibles para administradores. 
         * @summary Obtener software por ID
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSoftware: async (softwareId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'softwareId' is not null or undefined
            assertParamExists('getSoftware', 'softwareId', softwareId)
            const localVarPath = `/software/{software_id}`
                .replace(`{${"software_id"}}`, encodeURIComponent(String(softwareId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lista software disponible con filtros y paginación.
         * @summary Listar software
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {string} [category] Filtrar por categoría
         * @param {string} [search] Búsqueda por nombre o descripción
         * @param {string} [vendor] Filtrar por proveedor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSoftware: async (page?: number, pageSize?: number, category?: string, search?: string, vendor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/software`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (vendor !== undefined) {
                localVarQueryParameter['vendor'] = vendor;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Listar instaladores de un software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSoftwareInstallers: async (softwareId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'softwareId' is not null or undefined
            assertParamExists('listSoftwareInstallers', 'softwareId', softwareId)
            const localVarPath = `/software/{software_id}/installers`
                .replace(`{${"software_id"}}`, encodeURIComponent(String(softwareId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Solo Gestor y Administrador.
         * @summary Actualizar software
         * @param {number} softwareId 
         * @param {SoftwareUpdateRequest} softwareUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSoftware: async (softwareId: number, softwareUpdateRequest: SoftwareUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'softwareId' is not null or undefined
            assertParamExists('updateSoftware', 'softwareId', softwareId)
            // verify required parameter 'softwareUpdateRequest' is not null or undefined
            assertParamExists('updateSoftware', 'softwareUpdateRequest', softwareUpdateRequest)
            const localVarPath = `/software/{software_id}`
                .replace(`{${"software_id"}}`, encodeURIComponent(String(softwareId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(softwareUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SoftwareApi - functional programming interface
 * @export
 */
export const SoftwareApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SoftwareApiAxiosParamCreator(configuration)
    return {
        /**
         * Solo Gestor y Administrador.
         * @summary Crear software
         * @param {SoftwareCreateRequest} softwareCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSoftware(softwareCreateRequest: SoftwareCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SoftwareResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSoftware(softwareCreateRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SoftwareApi.createSoftware']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Solo Administrador. Elimina software y todos sus instaladores asociados (cascade). Los archivos físicos en FTP se eliminan también. 
         * @summary Eliminar software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSoftware(softwareId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSoftware(softwareId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SoftwareApi.deleteSoftware']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Detalles del software con lista de instaladores. Licencias solo visibles para administradores. 
         * @summary Obtener software por ID
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSoftware(softwareId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SoftwareDetailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSoftware(softwareId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SoftwareApi.getSoftware']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Lista software disponible con filtros y paginación.
         * @summary Listar software
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {string} [category] Filtrar por categoría
         * @param {string} [search] Búsqueda por nombre o descripción
         * @param {string} [vendor] Filtrar por proveedor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSoftware(page?: number, pageSize?: number, category?: string, search?: string, vendor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SoftwareListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSoftware(page, pageSize, category, search, vendor, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SoftwareApi.listSoftware']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @summary Listar instaladores de un software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSoftwareInstallers(softwareId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListSoftwareInstallers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSoftwareInstallers(softwareId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SoftwareApi.listSoftwareInstallers']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Solo Gestor y Administrador.
         * @summary Actualizar software
         * @param {number} softwareId 
         * @param {SoftwareUpdateRequest} softwareUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSoftware(softwareId: number, softwareUpdateRequest: SoftwareUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SoftwareResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSoftware(softwareId, softwareUpdateRequest, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['SoftwareApi.updateSoftware']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * SoftwareApi - factory interface
 * @export
 */
export const SoftwareApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SoftwareApiFp(configuration)
    return {
        /**
         * Solo Gestor y Administrador.
         * @summary Crear software
         * @param {SoftwareCreateRequest} softwareCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSoftware(softwareCreateRequest: SoftwareCreateRequest, options?: any): AxiosPromise<SoftwareResponse> {
            return localVarFp.createSoftware(softwareCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Solo Administrador. Elimina software y todos sus instaladores asociados (cascade). Los archivos físicos en FTP se eliminan también. 
         * @summary Eliminar software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSoftware(softwareId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteSoftware(softwareId, options).then((request) => request(axios, basePath));
        },
        /**
         * Detalles del software con lista de instaladores. Licencias solo visibles para administradores. 
         * @summary Obtener software por ID
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSoftware(softwareId: number, options?: any): AxiosPromise<SoftwareDetailResponse> {
            return localVarFp.getSoftware(softwareId, options).then((request) => request(axios, basePath));
        },
        /**
         * Lista software disponible con filtros y paginación.
         * @summary Listar software
         * @param {number} [page] Número de página (1-indexed)
         * @param {number} [pageSize] Elementos por página
         * @param {string} [category] Filtrar por categoría
         * @param {string} [search] Búsqueda por nombre o descripción
         * @param {string} [vendor] Filtrar por proveedor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSoftware(page?: number, pageSize?: number, category?: string, search?: string, vendor?: string, options?: any): AxiosPromise<SoftwareListResponse> {
            return localVarFp.listSoftware(page, pageSize, category, search, vendor, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Listar instaladores de un software
         * @param {number} softwareId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSoftwareInstallers(softwareId: number, options?: any): AxiosPromise<ListSoftwareInstallers200Response> {
            return localVarFp.listSoftwareInstallers(softwareId, options).then((request) => request(axios, basePath));
        },
        /**
         * Solo Gestor y Administrador.
         * @summary Actualizar software
         * @param {number} softwareId 
         * @param {SoftwareUpdateRequest} softwareUpdateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSoftware(softwareId: number, softwareUpdateRequest: SoftwareUpdateRequest, options?: any): AxiosPromise<SoftwareResponse> {
            return localVarFp.updateSoftware(softwareId, softwareUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SoftwareApi - object-oriented interface
 * @export
 * @class SoftwareApi
 * @extends {BaseAPI}
 */
export class SoftwareApi extends BaseAPI {
    /**
     * Solo Gestor y Administrador.
     * @summary Crear software
     * @param {SoftwareCreateRequest} softwareCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public createSoftware(softwareCreateRequest: SoftwareCreateRequest, options?: RawAxiosRequestConfig) {
        return SoftwareApiFp(this.configuration).createSoftware(softwareCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Solo Administrador. Elimina software y todos sus instaladores asociados (cascade). Los archivos físicos en FTP se eliminan también. 
     * @summary Eliminar software
     * @param {number} softwareId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public deleteSoftware(softwareId: number, options?: RawAxiosRequestConfig) {
        return SoftwareApiFp(this.configuration).deleteSoftware(softwareId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Detalles del software con lista de instaladores. Licencias solo visibles para administradores. 
     * @summary Obtener software por ID
     * @param {number} softwareId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public getSoftware(softwareId: number, options?: RawAxiosRequestConfig) {
        return SoftwareApiFp(this.configuration).getSoftware(softwareId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lista software disponible con filtros y paginación.
     * @summary Listar software
     * @param {number} [page] Número de página (1-indexed)
     * @param {number} [pageSize] Elementos por página
     * @param {string} [category] Filtrar por categoría
     * @param {string} [search] Búsqueda por nombre o descripción
     * @param {string} [vendor] Filtrar por proveedor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public listSoftware(page?: number, pageSize?: number, category?: string, search?: string, vendor?: string, options?: RawAxiosRequestConfig) {
        return SoftwareApiFp(this.configuration).listSoftware(page, pageSize, category, search, vendor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Listar instaladores de un software
     * @param {number} softwareId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public listSoftwareInstallers(softwareId: number, options?: RawAxiosRequestConfig) {
        return SoftwareApiFp(this.configuration).listSoftwareInstallers(softwareId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Solo Gestor y Administrador.
     * @summary Actualizar software
     * @param {number} softwareId 
     * @param {SoftwareUpdateRequest} softwareUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public updateSoftware(softwareId: number, softwareUpdateRequest: SoftwareUpdateRequest, options?: RawAxiosRequestConfig) {
        return SoftwareApiFp(this.configuration).updateSoftware(softwareId, softwareUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

// ✅ EXPORT para que otros módulos accedan al tipo
export type { SoftwareResponse, SoftwareCreateRequest } from '../models';