/* tslint:disable */
/* eslint-disable */
/**
 * Balaur SMS API
 * Software Management System para gestión, distribución y control de software universitario.  ## Características - Gestión de software con múltiples versiones - Sistema de archivos con FTP y validación SHA-256 - Licencias cifradas con AES-GCM - RBAC con 4 roles (Admin, Gestor, Usuario, Invitado) - Auditoría completa de operaciones - FTP Watcher automático para procesamiento de archivos  ## Autenticación La API utiliza JWT (Bearer tokens) con dos tipos de token: - **Access Token**: Válido 15 minutos - **Refresh Token**: Válido 7 días  ## Flujo de subida de instaladores 1. Usuario sube archivo vía FTP a `/inbox/pending/` 2. FTP Watcher procesa automáticamente (cada 5 min):    - Valida extensión y tamaño    - Calcula SHA-256    - Mueve a `/inbox/processing/` (si válido) o `/quarantine/` (si inválido) 3. Usuario registra instalador vía `POST /installers` con el SHA-256 4. Sistema organiza archivo en `/repository/software_id/version/` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@university.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InstallerResponse
 */
export interface InstallerResponse {
    /**
     * 
     * @type {number}
     * @memberof InstallerResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof InstallerResponse
     */
    'software_id': number;
    /**
     * Versión del software (ej. \"2.5.1\", \"2024.1\")
     * @type {string}
     * @memberof InstallerResponse
     */
    'version': string;
    /**
     * 
     * @type {string}
     * @memberof InstallerResponse
     */
    'filename': string;
    /**
     * Tamaño en bytes
     * @type {number}
     * @memberof InstallerResponse
     */
    'file_size': number;
    /**
     * Tamaño en MB (computed field)
     * @type {number}
     * @memberof InstallerResponse
     */
    'file_size_mb'?: number;
    /**
     * Tamaño en GB (computed field)
     * @type {number}
     * @memberof InstallerResponse
     */
    'file_size_gb'?: number;
    /**
     * 
     * @type {string}
     * @memberof InstallerResponse
     */
    'sha256_hash': string;
    /**
     * x64, x86, arm64, universal
     * @type {string}
     * @memberof InstallerResponse
     */
    'architecture'?: string | null;
    /**
     * Windows, Linux, macOS
     * @type {string}
     * @memberof InstallerResponse
     */
    'platform'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InstallerResponse
     */
    'notes'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InstallerResponse
     */
    'download_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof InstallerResponse
     */
    'uploaded_by'?: number;
    /**
     * 
     * @type {string}
     * @memberof InstallerResponse
     */
    'created_at': string;
}

