/* tslint:disable */
/* eslint-disable */
/**
 * Balaur SMS API
 * Software Management System para gestión, distribución y control de software universitario.  ## Características - Gestión de software con múltiples versiones - Sistema de archivos con FTP y validación SHA-256 - Licencias cifradas con AES-GCM - RBAC con 4 roles (Admin, Gestor, Usuario, Invitado) - Auditoría completa de operaciones - FTP Watcher automático para procesamiento de archivos  ## Autenticación La API utiliza JWT (Bearer tokens) con dos tipos de token: - **Access Token**: Válido 15 minutos - **Refresh Token**: Válido 7 días  ## Flujo de subida de instaladores 1. Usuario sube archivo vía FTP a `/inbox/pending/` 2. FTP Watcher procesa automáticamente (cada 5 min):    - Valida extensión y tamaño    - Calcula SHA-256    - Mueve a `/inbox/processing/` (si válido) o `/quarantine/` (si inválido) 3. Usuario registra instalador vía `POST /installers` con el SHA-256 4. Sistema organiza archivo en `/repository/software_id/version/` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@university.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LicenseType } from './license-type';

/**
 * 
 * @export
 * @interface LicenseCreateRequest
 */
export interface LicenseCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof LicenseCreateRequest
     */
    'software_id': number;
    /**
     * 
     * @type {LicenseType}
     * @memberof LicenseCreateRequest
     */
    'license_type': LicenseType;
    /**
     * Será cifrada con AES-GCM
     * @type {string}
     * @memberof LicenseCreateRequest
     */
    'license_key': string;
    /**
     * 
     * @type {number}
     * @memberof LicenseCreateRequest
     */
    'max_activations'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LicenseCreateRequest
     */
    'expiration_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LicenseCreateRequest
     */
    'notes'?: string | null;
}



