/* tslint:disable */
/* eslint-disable */
/**
 * Balaur SMS API
 * Software Management System para gestión, distribución y control de software universitario.  ## Características - Gestión de software con múltiples versiones - Sistema de archivos con FTP y validación SHA-256 - Licencias cifradas con AES-GCM - RBAC con 4 roles (Admin, Gestor, Usuario, Invitado) - Auditoría completa de operaciones - FTP Watcher automático para procesamiento de archivos  ## Autenticación La API utiliza JWT (Bearer tokens) con dos tipos de token: - **Access Token**: Válido 15 minutos - **Refresh Token**: Válido 7 días  ## Flujo de subida de instaladores 1. Usuario sube archivo vía FTP a `/inbox/pending/` 2. FTP Watcher procesa automáticamente (cada 5 min):    - Valida extensión y tamaño    - Calcula SHA-256    - Mueve a `/inbox/processing/` (si válido) o `/quarantine/` (si inválido) 3. Usuario registra instalador vía `POST /installers` con el SHA-256 4. Sistema organiza archivo en `/repository/software_id/version/` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@university.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProcessingFileResponse
 */
export interface ProcessingFileResponse {
    /**
     * 
     * @type {string}
     * @memberof ProcessingFileResponse
     */
    'filename': string;
    /**
     * 
     * @type {number}
     * @memberof ProcessingFileResponse
     */
    'size': number;
    /**
     * 
     * @type {string}
     * @memberof ProcessingFileResponse
     */
    'sha256': string;
    /**
     * Fecha de validación (ISO format)
     * @type {string}
     * @memberof ProcessingFileResponse
     */
    'validated_date': string;
    /**
     * 
     * @type {number}
     * @memberof ProcessingFileResponse
     */
    'size_mb'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessingFileResponse
     */
    'size_gb'?: number;
}

