/* tslint:disable */
/* eslint-disable */
/**
 * Balaur SMS API
 * Software Management System para gestión, distribución y control de software universitario.  ## Características - Gestión de software con múltiples versiones - Sistema de archivos con FTP y validación SHA-256 - Licencias cifradas con AES-GCM - RBAC con 4 roles (Admin, Gestor, Usuario, Invitado) - Auditoría completa de operaciones - FTP Watcher automático para procesamiento de archivos  ## Autenticación La API utiliza JWT (Bearer tokens) con dos tipos de token: - **Access Token**: Válido 15 minutos - **Refresh Token**: Válido 7 días  ## Flujo de subida de instaladores 1. Usuario sube archivo vía FTP a `/inbox/pending/` 2. FTP Watcher procesa automáticamente (cada 5 min):    - Valida extensión y tamaño    - Calcula SHA-256    - Mueve a `/inbox/processing/` (si válido) o `/quarantine/` (si inválido) 3. Usuario registra instalador vía `POST /installers` con el SHA-256 4. Sistema organiza archivo en `/repository/software_id/version/` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@university.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WatcherStatsResponse
 */
export interface WatcherStatsResponse {
    /**
     * Archivos en inbox/pending
     * @type {number}
     * @memberof WatcherStatsResponse
     */
    'pending': number;
    /**
     * Archivos en inbox/processing
     * @type {number}
     * @memberof WatcherStatsResponse
     */
    'processing': number;
    /**
     * Archivos en quarantine
     * @type {number}
     * @memberof WatcherStatsResponse
     */
    'quarantine': number;
    /**
     * Estado del watcher
     * @type {boolean}
     * @memberof WatcherStatsResponse
     */
    'is_running': boolean;
    /**
     * Intervalo de ejecución en segundos
     * @type {number}
     * @memberof WatcherStatsResponse
     */
    'interval_seconds': number;
    /**
     * Última ejecución (ISO)
     * @type {string}
     * @memberof WatcherStatsResponse
     */
    'last_run'?: string | null;
    /**
     * Próxima ejecución (ISO)
     * @type {string}
     * @memberof WatcherStatsResponse
     */
    'next_run'?: string | null;
    /**
     * Estadísticas de la última ejecución
     * @type {{ [key: string]: any; }}
     * @memberof WatcherStatsResponse
     */
    'last_run_stats'?: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof WatcherStatsResponse
     */
    'recent_errors'?: Array<string>;
    /**
     * Rutas configuradas
     * @type {{ [key: string]: any; }}
     * @memberof WatcherStatsResponse
     */
    'paths'?: { [key: string]: any; };
}

